/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2023.1.2304252251
    Soft IP Version: 1.4.0
    2023 04 28 13:32:38
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module osc0 (hf_out_en_i, hf_clk_out_o, lf_clk_out_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  hf_out_en_i;
    output  hf_clk_out_o;
    output  lf_clk_out_o;
endmodule